import type { Metadata } from "next";
import { Poppins, Source_Code_Pro } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins"
});

const sourcecode = Source_Code_Pro({
  weight: ["200", "300", "400", "500", "600"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sourcecode"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.variable} ${sourcecode.variable}`}>
      <body className={" min-h-full flex flex-col"}>
        {children}
      </body>
    </html>
  );
}